### ISSUE TITLE
image tag not found

### ISSUE THREAD

**Issue by BlackRider97** [odd-poet/dockers#1]
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.main", line 31, in main
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.command", line 28, in dispatch
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.command", line 56, in perform_command
  File "/code/build/fig/out00-PYZ.pyz/fig.cli.main", line 427, in up
  File "/code/build/fig/out00-PYZ.pyz/fig.project", line 174, in up
  File "/code/build/fig/out00-PYZ.pyz/fig.service", line 199, in recreate_containers
  File "/code/build/fig/out00-PYZ.pyz/fig.service", line 187, in create_container
  File "/code/build/fig/out00-PYZ.pyz/fig.progress_stream", line 37, in stream_output
  File "/code/build/fig/out00-PYZ.pyz/fig.progress_stream", line 50, in print_output_event
fig.progress_stream.StreamOutputError: Error: image oddpoet/hbase-cdh5.2: not found

**Comment by odd-poet** [comment]
Hello. 

try to use oddpoet/hbase-local:cdh5.2 instead of oddpoet/hbase-cdh5.2. 

https://registry.hub.docker.com/u/oddpoet/hbase-local/

-- 
yunsang.choi
Sent with Airmail

켜짐 2015년 1월 8일 에서 오전 3:42:23, Mitharwal Rajneesh (notifications@github.com) 작성됨:

Traceback (most recent call last):
File "", line 3, in
File "/code/build/fig/out00-PYZ.pyz/fig.cli.main", line 31, in main
File "/code/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
File "/code/build/fig/out00-PYZ.pyz/fig.cli.command", line 28, in dispatch
File "/code/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
File "/code/build/fig/out00-PYZ.pyz/fig.cli.command", line 56, in perform_command
File "/code/build/fig/out00-PYZ.pyz/fig.cli.main", line 427, in up
File "/code/build/fig/out00-PYZ.pyz/fig.project", line 174, in up
File "/code/build/fig/out00-PYZ.pyz/fig.service", line 199, in recreate_containers
File "/code/build/fig/out00-PYZ.pyz/fig.service", line 187, in create_container
File "/code/build/fig/out00-PYZ.pyz/fig.progress_stream", line 37, in stream_output
File "/code/build/fig/out00-PYZ.pyz/fig.progress_stream", line 50, in print_output_event
fig.progress_stream.StreamOutputError: Error: image oddpoet/hbase-cdh5.2: not found
